# © 2026 Tadi Srimannarayana Reddi. All Rights Reserved.
spring:
  application:
    name: order-service

  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.sriman.orderservice: INFO
    org.springframework.kafka: WARN
